/* eslint-disable */
// Generated by TanStack Router. This file is intentionally checked in so the
// project type-checks before the Vite plugin regenerates it.
import { Route as rootRoute } from "./routes/__root";
import { Route as indexRoute } from "./routes/index";
import { Route as searchRoute } from "./routes/search";
import { Route as movieDetailRoute } from "./routes/movies.$movieId";

const routeTree = rootRoute.addChildren([
  indexRoute,
  searchRoute,
  movieDetailRoute,
]);

export { routeTree };
